SpokenTutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('tts/', include('tts.urls')),
    path('videomerge/', include('videomerge.urls')),
]

base/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name="home"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="tts"),
    path('<str:id>/', views.download_speech, name='download-audio'),
]

videomerge/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.video, name="videomerge"),
    path('download/<str:id>/', views.download_video, name='download-video'),
    path('preview/<str:id>/', views.preview_video, name='preview-video'),
]

base/models.py
from django.db import models

# Create your models here.

tts/models.py
from django.db import models
from uuid import uuid4

class textToSpeech(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=True)
    text_file = models.FileField(upload_to='audio/temp')
    speech = models.FileField(upload_to='audio')

    def __str__(self):
        return str(self.text_id)

videomerge/models.py
from django.db import models
import uuid

# Function for Renaming file on upload
def file_rename(instance, filename):
    ext = filename.split('.')[-1]
    return f'video/temp/{instance.id}.{ext}'

# Model for storing converted videos
class convertedVideo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True)
    video = models.FileField(upload_to=file_rename)
    audio = models.FileField(upload_to=file_rename)
    output_video = models.FileField(upload_to='video')

    def __str__(self):
        return str(self.video_id)

base/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'base/home.html')

tts/views.py
from uuid import uuid4
from django.http import HttpResponse
from django.shortcuts import render
from django.core.files import File
from .func import convertToSpeech
from .models import textToSpeech
import os


def index(request):
    if request.method == 'POST' and request.FILES:
        txt = request.FILES['txt']
        # Checking the uploaded file whether it is '.txt' or not
        if txt.name[-3:] != 'txt':
            return render(request, 'tts/tts.html', {'message': True})


        voice = request.POST['voice']
        id = str(uuid4())
        textToSpeech(id=id, text_file=txt).save()

        obj = textToSpeech.objects.get(id=id)
        
        # Error handling, if gtts or pyttsx3 gives error
        try:
            url = convertToSpeech(obj.text_file.url[1:], voice)
            with open(url, 'rb') as f:
                obj.speech = File(f, f'{id}.mp3')
                obj.text_file.delete()
                obj.save()

            os.remove(url)
            # return the template with data
            return render(request, 'tts/tts.html', {'data': obj})

        # if error occurs the delete uploaded text file and the corresponding object
        except:
            obj.text_file.delete()
            obj.save()
            obj.delete()
            # return the template with error
            return render(request, 'tts/tts.html', {'error': True})
    
    # return the template
    return render(request, 'tts/tts.html')

# Response function for file downloading
def download_speech(request, id):
    # getting the video using id
    obj = textToSpeech.objects.get(id=id)

    # storing file path 
    fl_path = obj.speech.url[1:]
    filename = 'speech.mp3'      # downloadable filename

    # Opening file and serving as response
    fl = open(fl_path, 'rb')
    response = HttpResponse(fl, content_type='audio/mpeg')
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

videomerge/views.py
import os
from uuid import uuid4
from django.core.files import File
from django.http import HttpResponse
from django.shortcuts import render
from videomerge.func import convert_video
from videomerge.models import convertedVideo

vid_ext = ['mp4', 'mov', 'wmv', 'avi', 'mkv']   # Video file extensions
aud_ext = ['mp3', 'aac', 'ogg', 'wav']          # Audio file extensions

# Views to process video and audio merging and compression
def video(request):
    if request.method == 'POST' and request.FILES:
        video = request.FILES['video']
        audio = request.FILES['audio']
        # File validation check
        if video.name[-3:] not in vid_ext and audio.name[-3:] not in aud_ext:
            return render(request, 'videomerge/videomerge.html', {'message': True})

        id = str(uuid4())
        # storing audio and video in the model and saving it to media directory
        convertedVideo(id=id, video=video, audio=audio).save()

        # gettting object with unique id for processing
        obj = convertedVideo.objects.get(id=id)

        # Error handling, if ffmpeg or anything else gives error
        try:
            url = convert_video(obj.video.url[1:], obj.audio.url[1:])
            with url.open(mode='rb') as f:
                obj.output_video = File(f, f'{id}.mp4')
                obj.video.delete()
                obj.audio.delete()
                obj.save()
            os.remove(url)
        # if error occurs the delete uploaded video and audio files and the corresponding object
        except:
            obj.video.delete()
            obj.audio.delete()
            obj.save()
            obj.delete()
            # return the template with error
            return render(request, 'videomerge/videomerge.html', {'error': True})
            
        # return the template with data
        return render(request, 'videomerge/videomerge.html', {'data': obj})
    
    # return the template
    return render(request, 'videomerge/videomerge.html')



# Response function for file downloading
def download_video(request, id):
    # getting the video using id
    obj = convertedVideo.objects.get(id=id)

    # storing file path 
    fl_path = obj.output_video.url[1:]
    filename = 'converted_video.mp4'  # downloadable filename

    # Opening file and serving as response
    fl = open(fl_path, 'rb')
    response = HttpResponse(fl, content_type='video/mp4')
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

# View for video preview
def preview_video(request, id):
    # getting the video using id
    obj = convertedVideo.objects.get(id=id)
    # return the template with video preview
    return render(request, 'videomerge/preview.html', {'data': obj})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    <style>
        p {
            font-size: 20px;
        }

        h1 {
            text-align: center;
        }
    </style>

</head>

<body>
    <main>
        <div class="container py-4">
            {% include 'navbar.html' %}
            {% block content %}
            {% endblock %}

            <footer class="pt-3 mt-4 text-muted border-top">
                &copy; 2022 SpokenTutorial
            </footer>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

templates/base/home.html
{% extends "base.html" %}

{% block title %}
SpokenTutorial
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Home</h1>
    <hr class="my-4">


    <div class="row align-items-md-stretch">
        <div class="col-md-6">
            <div class="h-100 p-5 text-white bg-dark rounded-3">
                <h2>Text To Speech</h2>
                <p>Text To Speech takes a text file as input and gives a voiceover of it. You can upload your transcript as a text file and get it converted into speech within few seconds..</p>
                <a class="btn btn-outline-light" href={% url 'tts' %} role="button">Open TTS</a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="h-100 p-5 bg-light border rounded-3">
                <h2>VideoMerge</h2>
                <p>VideoMerge takes video and audio files as input and return a new video after merging and compressing it..</p>
                <a class="btn btn-outline-secondary" href={% url 'videomerge' %} role="button">Open VideoMerge</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <a class="navbar-brand" href={% url 'home' %}>SpokenTutorial</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href={% url 'home' %}>Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'tts' %}>Text To Speech</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'videomerge' %}>VideoMerge</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/tts/test.html
{% extends "base.html" %}

{% block title %}
Text To Speech
{% endblock %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Text To Speech</h1>
  <p class="lead text-center">Upload the text file and wait for few moments and experience the magic of Text To Speech
  </p>
  <hr class="my-4">

  <div class="row">
    <div class="col-sm">
      <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row mt-4 mb-4 pl-4 pr-4">
          <div class="col">
            {{form.as_p}}
            <label for="voice">Select Voice : </label>
            <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="voice">
              <option selected value="f">Female</option>
              <option value="m">Male</option>
            </select>
          </div>
          <button type="submit" class="btn btn-primary mt-2">Convert</button>
        </div>
      </form><br>
    </div>
    <div class="col-sm mt-4 mb-4 pl-4 pr-4">
      {% if data %}
      <p>Pre listen the audio before downloading</p>
      <audio controls controlsList="nodownload">
        <source src="{{ data.speech.url }}" type="audio/mpeg">
      </audio><br>
      <p>Download Audio : <a class="btn btn-outline-primary" href={% url 'download-audio' id=data.text_id %} role="button">Download</a></p>

      <!-- <a class="btn btn-outline-secondary" href="{{ request.META.HTTP_REFERER }}" role="button">Star Over</a> -->
      {% endif %}
    </div>
  </div>

  {% if error %}
  <div class="alert alert-warning" role="alert">
    <p>Internal Server Error, Sorry For inconvenience you faced. Please Try again. </p>
  </div>
  {% endif %}

  {% if message %}
  <div class="alert alert-warning" role="alert">
    <p>{{message}}</p>
  </div>
  {% endif %}
  {% endblock %}

templates/tts/tts.html
{% extends "base.html" %}

{% block title %}
Text To Speech
{% endblock %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Text To Speech</h1>
  <p class="lead text-center">Upload the text file and wait for few moments and experience the magic of Text To Speech
  </p>
  <hr class="my-4">

  <div class="row">
    <div class="col-sm">
      <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row mt-4 mb-4 pl-4 pr-4">
          <div class="col">
            <p>
              <label for="id_text_file">Upload Text file :</label>
              <input type="file" name="txt" required id="id_text_file">
            </p>
            <label for="voice">Select Voice : </label>
            <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="voice">
              <option selected value="f">Female</option>
              <option value="m">Male</option>
            </select>
          </div>
          <button type="submit" class="btn btn-primary mt-2">Convert</button>
        </div>
      </form><br>
    </div>
    <div class="col-sm mt-4 mb-4 pl-4 pr-4">
      {% if data %}
      <p>Pre listen the audio before downloading</p>
      <audio controls controlsList="nodownload">
        <source src="{{ data.speech.url }}" type="audio/mpeg">
      </audio><br>
      <p>Download Audio : <a class="btn btn-outline-primary" href={% url 'download-audio' id=data.id %} role="button">Download</a></p>

      <!-- <a class="btn btn-outline-secondary" href="{{ request.META.HTTP_REFERER }}" role="button">Star Over</a> -->
      {% endif %}
    </div>
  </div>

  {% if error %}
  <div class="alert alert-warning" role="alert">
    <p>Internal Server Error, Sorry For inconvenience you faced. Please Try again. </p>
  </div>
  {% endif %}

  {% if message %}
  <div class="alert alert-warning" role="alert">
    <p>Invalid File Format, only '.txt' files are Supported..</p>
  </div>
  {% endif %}
  {% endblock %}

templates/videomerge/preview.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Merge Video and Audio</h1>
  <hr class="my-4">
  <h2 class="text-center">Preview of The Video...</h2>
<center>
<video width="400" height="300" controls controlsList="nodownload">
  <source src="{{ data.output_video.url }}" type="video/mp4">
</video>
</center>
{% endblock %}

templates/videomerge/success.html
{% extends "base.html" %}
{% block content %}
<h1>Video and Audio Merge</h1>

<h3>Your Video has been merged and compressed successfully..</h3>

<video width="400" height="300" controls controlsList="nodownload">
  <source src="{{ data.output_video.url }}" type="video/mp4">
</video>
<p>Download Video : <a href={% url 'download-video' id=data.video_id %}>Download</a></p>
{% endblock %}

templates/videomerge/test.html
{% extends "base.html" %}

{% block title %}
Videomerge
{% endblock %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">VideoMerge</h1>
  <p class="lead text-center">Upload the video and audio file and wait for few moments and experience the magic of
    Videomerge</p>
  <hr class="my-4">

  <div class="row">
    <div class="col-sm">
      <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row mt-4 mb-4 pl-4 pr-4">
          <div class="col">
            {{form.as_p}}
          </div>
          <button type="submit" class="btn btn-primary btn-lg btn-block">Merge</button>
        </div>
      </form><br>
    </div>
    <div class="col-sm mt-4 mb-4 pl-4 pr-4">
      {% if data %}
      <p class="text-left">Your request has been processed.... </p><br>
      <p class="text-left">Preview Video: 
        <a class="btn btn-outline-secondary" href={% url 'preview-video' id=data.video_id %} role="button" target="_blank">Preview</a>
      </p><br>

      <p>OR Download Video: 
        <a class="btn btn-outline-primary" href={% url 'download-video' id=data.video_id %} role="button">Download</a>
      </p>
      {% endif %}
    </div>
  </div>


  {% if error %}
  <div class="alert alert-warning" role="alert">
    <p>Internal Server Error, Sorry For inconvenience you faced. Please Try again. </p>
  </div>
  {% endif %}

  {% if message %}
  <div class="alert alert-warning" role="alert">
    <p>Invalid File Format, only '.txt' files are Supported..</p>
  </div>
  {% endif %}
</div>
{% endblock %}

templates/videomerge/videomerge.html
{% extends "base.html" %}

{% block title %}
Videomerge
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">VideoMerge</h1>
    <p class="lead text-center">Upload the video and audio file and wait for few moments and experience the magic of
        Videomerge</p>
    <hr class="my-4">

    <div class="row">
        <div class="col-sm">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row mt-4 mb-4 pl-4 pr-4">
                    <div class="col">
                        <p>
                            <label for="id_video">Video:</label>
                            <input type="file" name="video" required id="id_video">
                        </p>
                        <p>
                            <label for="id_audio">Audio:</label>
                            <input type="file" name="audio" required id="id_audio">
                        </p>
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Merge</button>
                </div>
            </form><br>
        </div>
        <div class="col-sm mt-4 mb-4 pl-4 pr-4">
            {% if data %}
            <p class="text-left">Your request has been processed.... </p><br>
            <p class="text-left">Preview Video:
                <a class="btn btn-outline-secondary" href={% url 'preview-video' id=data.id %} role="button"
                    target="_blank">Preview</a>
            </p><br>

            <p>OR Download Video:
                <a class="btn btn-outline-primary" href={% url 'download-video' id=data.id %}
                    role="button">Download</a>
            </p>
            {% endif %}
        </div>
    </div>


    {% if error %}
    <div class="alert alert-warning" role="alert">
        <p>Internal Server Error, Sorry For inconvenience you faced. Please Try again. </p>
    </div>
    {% endif %}

    {% if message %}
    <div class="alert alert-warning" role="alert">
        <p>Invalid File Format, only '.mp4' videos and '.mp3' audio files are Supported..</p>
    </div>
    {% endif %}
</div>
{% endblock %}